### ISSUE TITLE
Can't get producer and consumer to talk to each other

### ISSUE THREAD

**Issue by NightWhistler** [aloiscochard/sarsi#14]
I've been trying to get Sarsi to work, but I seem to be missing something.
The producer end seems to work just fine, but both sarsi-vi and sarsi-nvim never seem to receive any events.

I have installed from source.

What I'm trying to do:
 - I go to my project folder, and run 'sarsi-sbt'
 - In another shell, I also go to my project folder and run 'sarsi-vi'
 - In my sbt shell, I run 'compile'. I have deliberately created an error in my code, so that SBT gives me a compile error
 - At  this point I expect sarsi-vi to give me some sort of output, but it doesn't.

Debugging steps:

 - I go to my project folder, and run 'sarsi'. This gives me the name of the Unix socket for that folder
 - I run 'sarsi-sbt' in my project folder
 - I verify that the domain socket is created (which it is)
 - I run 'nc -U /tmp/sarsi/[socket-id]'
 - I run 'compile' in the SBT shell

At this point, nc produces some output both when the build starts, and when SBT gives the compile error. This leads me to conclude that the producing end works, but that the consomers somehow can't connect to the socket or are otherwhise quietly failing.

Could you give me some guidance in how to further debug this issue?

**Comment by NightWhistler** [comment]
Not sure if it's relevant, but I'm on Ubuntu 16.04 and the reason I installed from source is because the cabal install failed.

**Comment by rminehan** [comment]
I hit the same issue with `nvim` and `sarsi-sbt`. Also on ubuntu 16.04 and also built from source at `1e78a64` because the cabal install failed.

**Comment by aloiscochard** [comment]
It's been a while, but I did refresh the project and found many edge case with unix pipe that were not covered (similar issues as described here).

If you still have interest in using this tool it should hopefully be robust, please open an new issue if you encounter a problem.
