### ISSUE TITLE
Investigate interactive issue with sbt >= 1.4

### ISSUE THREAD

**Issue by aloiscochard** [aloiscochard/sarsi#18]
It looks like the "hacked" pipe trick is not playing well with the new curses interface.

**Comment by aloiscochard** [comment]
Alternatively, we could use `sbt --client` approach and have a unified interface.

**Comment by tdroxler** [comment]
I quickly made the following test https://github.com/tdroxler/sarsi/commit/b0d6e5050fc1b0c0611821c4d22b7e5e17e33f3e and we are already close, we still have the problem of the relative path, but I'm not sure how we can access the `topicOrigin`

**Comment by aloiscochard** [comment]
@tdroxler please see https://github.com/aloiscochard/sarsi/pull/20, disclaimer: I have not tested it for real, but oh well, it compiles.

**Comment by aloiscochard** [comment]
I made progress, but sadly it's still not fully working:

1. When running as pipe (using `srs` or `sarsi`) the producer send twice the same error, but second time with the string "[error] " prepended to the filepath.
2. When running thru `sarsi-sbt` it mangle input, if we fix the problem above we could consider make `sarsi-sbt` legacy for sbt >= 1.14, and instead revisist later thru a generic wrapper for interactive process.

**Comment by aloiscochard** [comment]
Note: I made many improvment in #21 regarding escape control character, so this might improve problem 1 above.

**Comment by tdroxler** [comment]
I could isolate the two issues I see for sbt >= 1.4

It's explained in the two last commits here: https://github.com/tdroxler/sarsi/commits/thomas-test

Basically: 
 - The Project processor is also sending the sbt error to the client, thus the error is doubled.
 -  The Haskell parser is getting a hit on the sbt error, returning the error but with a wrong format.
