### ISSUE TITLE
it doesn't work with `sarsi-hs stack build --file-watch`

### ISSUE THREAD

**Issue by rvion** [aloiscochard/sarsi#5]
it doesn't work with `sarsi-hs stack build --file-watch`
Neovim never get notified.

**Comment by aloiscochard** [comment]
@rvion Hi Rémi, sorry it does not works with stack `--file-watch`.

The thing is it was designed to work quite generically, for example with `entr` like: https://github.com/aloiscochard/sarsi#haskell

But the same command could use to parse directly cabal/ghc output.

If you are interested to support `--file-watch`, please create an issue for a `sarsi-stack` equivalent to what `sarsi-sbt` is for Scala.

Thanks!
